name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Chạy khi push lên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/learnking-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/learnking-backend:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/LearnKing || mkdir ~/LearnKing && cd ~/LearnKing
            echo "${{ secrets.DB_CONNECTION_STRING }}" > .env
            docker pull ${{ secrets.DOCKER_USERNAME }}/learnking-backend:latest
            docker stop learnking-backend || true
            docker rm learnking-backend || true
            docker run -d --name learnking-backend -p 5005:86 --env-file .env ${{ secrets.DOCKER_USERNAME }}/learnking-backend:latest
            docker image prune -f
